### PR TITLE
Setup GitHub Actions

### PR DESCRIPTION
**Pull request by RedFoxFinn**
rewrite for GitHub Actions Workflow file to reflect better changed and changing codebase and pipeline

### CODE REVIEW

**Comment by RedFoxFinn** [comment]
Workflow file updated, running currently up to linter, which exclaims of unused variables.

Missing database setup for testing.

**Comment by vejol** [comment]
**This pull request will do following things:**
- Create GitHub Actions with two actions:
  1. When creating pull request or adding commits to pull requests, run tests
  2. When pushing to main (ie. accepting pull request) run tests and then push frontend and backend images to quay.io with tag 'staging'
- Simplify Sequelize and Sequelize CLI setup
  - All environments use DATABASE_URL env variable for establishing connection
  - sequelize logging is turned off now even in production as seems not to be handy
- Dockerfiles install only dependencies for production
  - devDependencies are not needed in production 
  - This will decrease image size and make building images faster
- homepage in package.json is set /projekti
  - Earlier it was pointing to our OpenShift test environment and it may be confusing because this is also used in other environments such as production and test environment
  - Only last part of the address is needed and I have tested that /projekti works in staging, too

**Review by Regularmute — COMMENTED** [review]
Things look otherwise alright, but a test is failing with rendering "all configurations", are you aware of this or should I wait for it to be fixed before merging?

**Review by Regularmute — APPROVED** [review]
The failing test is a known issue, approved for merging nonetheless.

**Pull request merged**
