### PR TITLE
Define licence on project root

### PR DESCRIPTION
**Pull request by vejol**
This pull request moves licence definition to project root.

### CODE REVIEW

**Comment by miahro** [comment]
License change is good. 

Why change in .eslintrc.js? I think we should keep
  ignorePatterns: ['e2e/'],

Can you comment or revert this change back?

**Comment by vejol** [comment]
I changed .eslintrc as previous change ignorePatterns broke the linter. I got error message when trying to run "npm run lint" or making comment (husky lint check produces error). Also Ismo got same errors and we didin't find solution yet.

@miahro Can you run "npm run lint" in frontend folder in current main? And have you tried make a commit?

**Comment by miahro** [comment]
@vejol eslint updated, .eslintrc reverted back & one lint error fixed.

**Review by vejol — COMMENTED** [review]
Looks good!

**Review by ismomehdi — APPROVED** [review]
All good!

**Pull request merged**
